const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const HOST='127.0.0.1',PORT=Number(process.env.PORT)||3000,ROOT=__dirname,DATA_DIR=path.join(ROOT,'data'),DATA_FILE=path.join(DATA_DIR,'appointments.json');
const TYPES={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.jpg':'image/jpeg'};
const SERVICES=new Set(['Signature Facial','Acne Treatment','Anti-Aging Therapy','Laser Treatment','Skin Brightening','Chemical Peel','Hydra Facial']);
fs.mkdirSync(DATA_DIR,{recursive:true});if(!fs.existsSync(DATA_FILE))fs.writeFileSync(DATA_FILE,'[]\n');
function json(res,status,body){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(body));}
function validate(v){if(!v.name||String(v.name).trim().length<2)return'Please enter a valid name.';if(!/^[+\d][\d\s()-]{7,}$/.test(String(v.phone||'')))return'Please enter a valid phone number.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v.email||'')))return'Please enter a valid email address.';if(!SERVICES.has(v.service))return'Please select a valid service.';const d=new Date(`${v.date}T00:00:00`),today=new Date();today.setHours(0,0,0,0);if(!v.date||Number.isNaN(d.getTime())||d<today)return'Please select a current or future date.';if(String(v.message||'').length>1000)return'Message must be under 1,000 characters.';return null;}
function save(v){const records=JSON.parse(fs.readFileSync(DATA_FILE,'utf8')),reference=`LSC-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;records.push({id:crypto.randomUUID(),reference,...v,status:'new',createdAt:new Date().toISOString()});const tmp=`${DATA_FILE}.tmp`;fs.writeFileSync(tmp,`${JSON.stringify(records,null,2)}\n`);fs.renameSync(tmp,DATA_FILE);return reference;}
function api(req,res){let body='';req.on('data',c=>{body+=c;if(body.length>20000)req.destroy();});req.on('end',()=>{try{const p=JSON.parse(body||'{}'),error=validate(p);if(error)return json(res,400,{message:error});const safe={name:String(p.name).trim(),phone:String(p.phone).trim(),email:String(p.email).trim().toLowerCase(),service:p.service,date:p.date,message:String(p.message||'').trim()};json(res,201,{message:'Appointment request received.',reference:save(safe)});}catch(e){json(res,400,{message:'Invalid request data.'});}});}
const server=http.createServer((req,res)=>{if(req.method==='POST'&&req.url==='/api/appointments')return api(req,res);if(!['GET','HEAD'].includes(req.method))return json(res,405,{message:'Method not allowed.'});const pathname=decodeURIComponent(req.url.split('?')[0]),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=path.resolve(ROOT,relative),root=path.resolve(ROOT);if(!file.startsWith(`${root}${path.sep}`))return json(res,403,{message:'Forbidden.'});fs.stat(file,(error,stat)=>{if(error||!stat.isFile()){res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});return res.end('Not found');}res.writeHead(200,{'Content-Type':TYPES[path.extname(file).toLowerCase()]||'application/octet-stream','X-Content-Type-Options':'nosniff'});if(req.method==='HEAD')return res.end();fs.createReadStream(file).pipe(res);});});
server.listen(PORT,HOST,()=>console.log(`Lumière Skin Clinic is running at http://${HOST}:${PORT}`));
